global class userInformationVo {
       // Inner class to define the structure of user information
    
        public string Name { get; set; }
        public string WorkEmail { get; set; }
        public string PersonalEmail { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string HRManager { get; set; }
        public string EmployeeID {get; set;}
        public string ErrorMessage { get; set; }
    
     
}