public class UserInformationVOClass {
    public String Name { get; set; }
    public String WorkEmail { get; set; }
    public String PersonalEmail { get; set; }
    public String ResourceManager { get; set; }
    public Decimal Rating { get; set; }
    public String EmploymentType { get; set; }
    public Address Address { get; set; }
    public String Bench { get; set; }
    public String ContactNumber { get; set; }
    public String CurrentLevel { get; set; }
    public Decimal CurrentSalary { get; set; }
    public Date DateofBirth { get; set; }
    public String EmployeeID { get; set; }
    public String HRManager { get; set; }
    public String ProjectManager { get; set; }
    public String ReportingDirector { get; set; }
    public String ReportingManager { get; set; }
    public String RecrutingManager { get; set; }
    public Date JoinedDate { get; set; }
    public String WorkLocation { get; set; }
    public String Position { get; set; }
    public String RequiredDocumentsToUpload { get; set; }
    public String userType { get; set; }
    
 
}